"""update_to_sellers_table

Revision ID: 09ddeafba14c
Revises: 6c1dc4ba6c67
Create Date: 2024-05-04 13:08:02.265115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ddeafba14c'
down_revision: Union[str, None] = '6c1dc4ba6c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
