"""added_vendor_id_to_invoice_table

Revision ID: 2f9b254e6d05
Revises: bd9f8d74b902
Create Date: 2024-05-15 11:36:11.773798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9b254e6d05'
down_revision: Union[str, None] = 'bd9f8d74b902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('vendor_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'invoices', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'vendor_id')
    # ### end Alembic commands ###
