"""update_payments_table

Revision ID: 362c364d2f8d
Revises: 73716f2ab439
Create Date: 2024-05-24 00:37:29.465385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362c364d2f8d'
down_revision: Union[str, None] = '73716f2ab439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('payments', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.add_column('payments', sa.Column('vendor_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vendors', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'vendor_id')
    op.drop_column('payments', 'customer_id')
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('customers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
