"""add_payments_table_columns

Revision ID: 3b1de5ccc43b
Revises: 60b84bce8ea3
Create Date: 2024-05-22 10:38:44.742076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1de5ccc43b'
down_revision: Union[str, None] = '60b84bce8ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
