"""added_total_to_invoice_table

Revision ID: 60b84bce8ea3
Revises: 2f9b254e6d05
Create Date: 2024-05-15 18:38:29.996479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b84bce8ea3'
down_revision: Union[str, None] = '2f9b254e6d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('total', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'total')
    # ### end Alembic commands ###
