"""update_sellers_table

Revision ID: 859f6cdc1174
Revises: 67f863512936
Create Date: 2024-04-29 22:45:46.278492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859f6cdc1174'
down_revision: Union[str, None] = '67f863512936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('business_pic', sa.String(), nullable=True))
    op.add_column('sellers', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'address')
    op.drop_column('sellers', 'business_pic')
    # ### end Alembic commands ###
